#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$IOS_DIR/.." && pwd)"
MDBX_DIR="$REPO_ROOT/mdbx"
OUT_DIR="$IOS_DIR/Generated/MDBXUniFFI"
LIB_PATH="$MDBX_DIR/target/debug/libmdbx_ffi.dylib"

if ! command -v cargo >/dev/null 2>&1; then
  echo "cargo is required to build mdbx-ffi" >&2
  exit 1
fi

if ! command -v uniffi-bindgen-swift >/dev/null 2>&1; then
  if [ -x "$HOME/.cargo/bin/uniffi-bindgen-swift" ]; then
    export PATH="$HOME/.cargo/bin:$PATH"
  else
    echo "uniffi-bindgen-swift is required." >&2
    echo "Install it with: cargo install uniffi --version 0.31.1 --locked --features cli" >&2
    exit 1
  fi
fi

cd "$MDBX_DIR"
cargo build -p mdbx-ffi

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

uniffi-bindgen-swift --swift-sources "$LIB_PATH" "$OUT_DIR"
uniffi-bindgen-swift --headers "$LIB_PATH" "$OUT_DIR"
uniffi-bindgen-swift \
  --modulemap \
  --xcframework \
  --module-name MonicaMDBXGenerated \
  "$LIB_PATH" \
  "$OUT_DIR"

cat > "$OUT_DIR/README.md" <<'EOF'
# Generated UniFFI Bindings

This directory is generated by `Monica for iOS/Scripts/generate-mdbx-swift-bindings.sh`.

Do not edit generated Swift, header, or modulemap files manually.

The generated files are build artifacts until the iOS XCFramework packaging step
lands. They are intentionally kept outside SwiftPM `Sources` so package tests can
run before the device/simulator binary artifact is available.
EOF

echo "Generated Swift bindings in: $OUT_DIR"
